version: '3.8'

# NETWORK
networks:
  proxy:
    external: true
  du-network:
    driver: bridge

# SERVICES
services:
  frontend:
    build: ./frontend
    expose:
      - "3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - proxy
      - du-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      # Redirect HTTP ke HTTPS
      - "traefik.http.middlewares.du-redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.du-redirect-to-https.redirectscheme.permanent=true"

      # HTTP router
      - "traefik.http.routers.du-fe.rule=Host(`du.doscom.org`)"
      - "traefik.http.routers.du-fe.entrypoints=web"
      - "traefik.http.routers.du-fe.middlewares=du-redirect-to-https"
      - "traefik.http.routers.du-fe.priority=2000"

      # HTTPS router
      - "traefik.http.routers.du-fe-sec.rule=Host(`du.doscom.org`)"
      - "traefik.http.routers.du-fe-sec.entrypoints=websecure"
      - "traefik.http.routers.du-fe-sec.tls=true"
      - "traefik.http.routers.du-fe-sec.tls.certresolver=letsencryptresolver"
      - "traefik.http.routers.du-fe-sec.priority=2000"

      # service -> 3000
      - "traefik.http.routers.du-fe.service=du-fe-svc"
      - "traefik.http.routers.du-fe-sec.service=du-fe-svc"
      - "traefik.http.services.du-fe-svc.loadbalancer.server.port=3000"

  backend:
    build: ./backend
    ports:
      - "8080:8080" # Biarkan ports jika butuh diakses via IP langsung untuk testing
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - minio
    volumes:
      - ./backend:/app
    networks:
      - proxy
      - du-network

  db:
    image: postgres:15
    env_file:
      - ./backend/.env
    ports:
      - "5430:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - du-network

  adminer:
    image: adminer
    ports:
      - "8012:8080"
    networks:
      - du-network

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ./backend/.env
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - du-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  db_data:
  minio_data:
