# Build stage
FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o ./dist/backend main.go

# Runtime stage
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/dist/backend .
EXPOSE 8080
CMD ["./backend"]