import {
  ICardData,
  IDashboardStat,
  IDeadlineItem,
  IFeedbackItem,
  IProgramFeatures,
  IResumeCourse,
  PaymentStatus,
  TransactionHistoryItem,
  ICertificate,
  IAttendanceSummary,
  IAttendanceRecord,
  ICourseAttendance,
  IMentorStats,
  IScheduleItem,
  ISubmissionItem,
} from './types'
import { BookIcons, CertificateIcons, GlobeLearningIcon, JobIcons } from '@/components/ui/icons'

export const DataCourse: ICardData[] = [
  {
    variantBadge: 'event',
    title: 'Advanced React Patterns & Next.js 15 Architecture',
    description:
      'Berhenti menulis kode reaktif yang berantakan. Pelajari cara membangun aplikasi skala enterprise dengan teknik rendering hybrid, manajemen state terdesentralisasi, dan optimasi performa ekstrem.',
    category: 'Pengembangan Web',
    author: {
      name: 'Sarah Drasner',
      avatar: 'https://i.pravatar.cc/150?u=sarah_d',
    },
    rating: 4.9,
    totalReviews: 1450000,
    image: 'https://picsum.photos/seed/react/600/400',
  },
  {
    variantBadge: 'free',
    title: 'Figma to Code',
    description: 'Beralih dari mockup Figma murni menuju web interaktif dengan fundamental terstruktur.',
    category: 'Desain UI/UX',
    author: {
      name: 'Budi',
      avatar: 'https://i.pravatar.cc/150?u=budi_dev',
    },
    rating: 4.2,
    totalReviews: 125,
  },
  {
    variantBadge: 'premium',
    title: 'Machine Learning with Python: Zero to Hero',
    description: 'Kuasai algoritma prediksi, manipulasi data dengan Pandas, dan bangun model AI pertama Anda dalam 30 hari.',
    category: 'Data Science & AI',
    author: {
      name: 'Dr. Alex Chen',
      avatar: 'https://i.pravatar.cc/150?u=alex_c',
    },
    rating: 4.6,
    totalReviews: 8432,
    image: 'https://picsum.photos/seed/ml/600/400',
  },
  {
    variantBadge: 'event',
    title: 'UI/UX Fundamentals',
    description: 'Memahami hierarki visual, tipografi, dan spasi yang rasional. Berhenti menebak-nebak dan gunakan sistem.',
    category: 'Desain UI/UX',
    author: {
      name: 'Jessica Wong',
      avatar: 'https://i.pravatar.cc/150?u=jess_w',
    },
    rating: 4.8,
    totalReviews: 2450,
  },
  {
    variantBadge: 'free',
    title: 'Mastering Tailwind CSS v4 & Framer Motion',
    description: 'Eksplorasi animasi kompleks dan layout responsif tingkat lanjut menggunakan utility-first framework.',
    category: 'Pengembangan Web',
    author: {
      name: 'Marcus Levin',
      avatar: 'https://i.pravatar.cc/150?u=marcus_l',
    },
    rating: 5.0,
    totalReviews: 999,
    image: 'https://picsum.photos/seed/tailwind/600/400',
  },
  {
    variantBadge: 'premium',
    title: 'Rust for WebAssembly',
    description: 'Tingkatkan performa aplikasi web Anda hingga 10x lipat dengan mengkompilasi Rust ke Wasm.',
    category: 'Pengembangan Web',
    author: {
      name: 'Elena Rostova',
      avatar: 'https://i.pravatar.cc/150?u=elena_r',
    },
    rating: 4.8,
    totalReviews: 21500,
    image: 'https://picsum.photos/seed/rust/600/400',
  },
  // 10 Data Kursus Tambahan
  {
    variantBadge: 'premium',
    title: 'Cybersecurity Analyst Bootcamp',
    description: 'Analisis serangan dan ancaman cyber terkini. Praktek offensive hacking dengan tool industri nyata.',
    category: 'Cybersecurity',
    author: {
      name: 'Kevin Mitnick',
      avatar: 'https://i.pravatar.cc/150?u=kevin_m',
    },
    rating: 4.9,
    totalReviews: 54100,
    image: 'https://picsum.photos/seed/cyber/600/400',
  },
  {
    variantBadge: 'free',
    title: 'Data Analytics dengan Tableau',
    description: 'Pahami cara memodelkan data mentah dan merubahnya menjadi visualisasi tabel dinamis yang profesional.',
    category: 'Data Science & AI',
    author: {
      name: 'Jordan Walke',
      avatar: 'https://i.pravatar.cc/150?u=jordan_w',
    },
    rating: 4.5,
    totalReviews: 1250,
  },
  {
    variantBadge: 'premium',
    title: 'Product Management Strategy',
    description: 'Strategi membangun produk yang digemari pasar dari ideasi hingga monetisasi berdasarkan metrik.',
    category: 'Bisnis & Manajemen',
    author: {
      name: 'Martin Fowler',
      avatar: 'https://i.pravatar.cc/150?u=martin_f',
    },
    rating: 4.7,
    totalReviews: 890,
    image: 'https://picsum.photos/seed/business/600/400',
  },
  {
    variantBadge: 'draft',
    title: 'Pengantar Vue 3 Composition API',
    description: 'Fundamental menggunakan framework antarmuka Vue.js terbaru secara reaktif.',
    category: 'Pengembangan Web',
    author: {
      name: 'Evan You',
      avatar: 'https://i.pravatar.cc/150?u=evan_y',
    },
    rating: 4.3,
    totalReviews: 55,
  },
  {
    variantBadge: 'premium',
    title: 'Figma Pro Prototyping',
    description: 'Buat animasi mutakhir dan smart animate antarmuka terintegrasi pada layout prototip web modern Anda.',
    category: 'Desain UI/UX',
    author: {
      name: 'DesignCourse',
      avatar: 'https://i.pravatar.cc/150?u=gary_s',
    },
    rating: 4.8,
    totalReviews: 450,
    image: 'https://picsum.photos/seed/proto/600/400',
  },
  {
    variantBadge: 'premium',
    title: 'Mastering Linux & Ethical Hacking',
    description: 'Menyelam jauh ke sistem dasar Linux untuk testing injeksi dan deteksi kelemahan jaringan internal.',
    category: 'Cybersecurity',
    author: {
      name: 'Linus B.',
      avatar: 'https://i.pravatar.cc/150?u=linus_b',
    },
    rating: 4.9,
    totalReviews: 11000,
  },
  {
    variantBadge: 'free',
    title: 'Lean Startup for Digital Nomads',
    description: 'Panduan membangun bisnis rintisan tanpa perlu pendanaan besar memanfaatkan ide dan validasi gesit.',
    category: 'Bisnis & Manajemen',
    author: {
      name: 'Eric Ries',
      avatar: 'https://i.pravatar.cc/150?u=eric_r',
    },
    rating: 4.5,
    totalReviews: 331,
  },
  {
    variantBadge: 'event',
    title: 'Deep Learning x Finance Market',
    description: 'Penggunaan machine learning mutakhir untuk analisis sentimen pasar finansial secara real-time.',
    category: 'Data Science & AI',
    author: {
      name: 'Andrew Ng',
      avatar: 'https://i.pravatar.cc/150?u=andrew_n',
    },
    rating: 5.0,
    totalReviews: 955,
    image: 'https://picsum.photos/seed/financeai/600/400',
  },
  {
    variantBadge: 'premium',
    title: 'Go (Golang) Microservices',
    description: 'Sistem dan bahasa berkinerja tinggi. Bangun server API tercepat via gRPC dan mekanisme goroutines.',
    category: 'Pengembangan Web',
    author: {
      name: 'Rob Pike',
      avatar: 'https://i.pravatar.cc/150?u=rob_p',
    },
    rating: 4.7,
    totalReviews: 240,
  },
  {
    variantBadge: 'event',
    title: 'Social Media Organic Marketing',
    description: 'Teknik efisien mengembangkan audiens audiens murni menggunakan personal branding yang terorganisir.',
    category: 'Bisnis & Manajemen',
    author: {
      name: 'Gary Vaynerchuk',
      avatar: 'https://i.pravatar.cc/150?u=gary_v',
    },
    rating: 4.8,
    totalReviews: 6990,
  },
]

export const ProgramFeatures: IProgramFeatures[] = [
  {
    title: 'Materi Open Source & Gratis',
    description: 'Belajar tanpa hambatan biaya dengan kurikulum yang dikembangkan secara terbuka oleh komunitas.',
    icon: <BookIcons />,
  },
  {
    title: 'Project-Based Learning',
    description: 'Kamu tidak hanya menonton video, tapi langsung membangun portofolio nyata untuk melamar kerja.',
    icon: <GlobeLearningIcon />,
  },
  {
    title: 'Kurikulum standar industri',
    description: 'Materi yang disusun berdasarkan kebutuhan dunia kerja nyata, bukan sekadar teori teks buku.',
    icon: <JobIcons />,
  },
  {
    title: 'Sertifikat Eksklusif',
    description: 'Dapatkan bukti kompetensi yang diakui untuk meningkatkan nilai jual kamu di pasar kerja.',
    icon: <CertificateIcons />,
  },
]

export const DashboardStats: IDashboardStat[] = [
  { label: 'Total Kursus', value: 12, iconName: 'Book' },
  { label: 'Materi Selesai', value: 84, iconName: 'ClipboardCheck' },
  { label: 'Total Sertifikat', value: 5, iconName: 'Award' },
  { label: 'Kursus Selesai', value: 4, iconName: 'CheckCircle' },
]

export const ResumeCourses: IResumeCourse[] = [
  {
    title: 'Mastering UI/UX Design: From Zero to Hero',
    description: 'Pelajari dasar-dasar desain antarmuka pengguna, prototyping, dan cara membangun pengalaman pengguna yang memukau.',
    module: 'Modul 4 dari 12',
    progress: 100,
    image: 'https://picsum.photos/seed/uidesign/400/300',
    variantBadge: 'premium',
    author: {
      name: 'Jessica Wong',
      avatar: 'https://i.pravatar.cc/150?u=jess_w',
    },
    rating: 4.8,
    totalReviews: 2450,
  },
  {
    title: 'Web Development with React & Next.js',
    description: 'Bangun aplikasi web modern menggunakan React dan Next.js dengan arsitektur yang scalable.',
    module: 'Modul 7 dari 10',
    progress: 42,
    image: 'https://picsum.photos/seed/webdev/400/300',
    variantBadge: 'free',
    author: {
      name: 'Sarah Drasner',
      avatar: 'https://i.pravatar.cc/150?u=sarah_d',
    },
    rating: 4.9,
    totalReviews: 8432,
  },
  {
    title: 'Data Structure & Algorithm',
    description: 'Kuasai algoritma analisis, struktur data, dan persiapkan diri Anda untuk wawancara teknis di perusahaan top.',
    module: 'Modul 2 dari 8',
    progress: 18,
    variantBadge: 'event',
    author: {
      name: 'Dr. Alex Chen',
      avatar: 'https://i.pravatar.cc/150?u=alex_c',
    },
    rating: 4.6,
    totalReviews: 1250,
  },
  {
    title: 'Mastering UI/UX Design: From Zero to Hero',
    description: 'Pelajari dasar-dasar desain antarmuka pengguna, prototyping, dan cara membangun pengalaman pengguna yang memukau.',
    module: 'Modul 4 dari 12',
    progress: 75,
    image: 'https://picsum.photos/seed/uidesign/400/300',
    variantBadge: 'premium',
    author: {
      name: 'Jessica Wong',
      avatar: 'https://i.pravatar.cc/150?u=jess_w',
    },
    rating: 4.5,
    totalReviews: 1450,
  },
  {
    title: 'Web Development with React & Next.js',
    description: 'Bangun aplikasi web modern menggunakan React dan Next.js dengan arsitektur yang scalable.',
    module: 'Modul 7 dari 10',
    progress: 42,
    image: 'https://picsum.photos/seed/webdev/400/300',
    variantBadge: 'free',
    author: {
      name: 'Sarah Drasner',
      avatar: 'https://i.pravatar.cc/150?u=sarah_d',
    },
    rating: 4.9,
    totalReviews: 8432,
  },
  {
    title: 'Data Structure & Algorithm',
    description: 'Kuasai algoritma analisis, struktur data, dan persiapkan diri Anda untuk wawancara teknis di perusahaan top.',
    module: 'Modul 2 dari 8',
    progress: 18,
    variantBadge: 'event',
    author: {
      name: 'Dr. Alex Chen',
      avatar: 'https://i.pravatar.cc/150?u=alex_c',
    },
    rating: 4.7,
    totalReviews: 1250,
  },
]

export const Deadlines: IDeadlineItem[] = [
  {
    month: 'Okt',
    day: '24',
    title: 'Analisis User Flow - E-Commerce App',
    course: 'Interaksi Manusia & Komputer',
  },
  {
    month: 'Okt',
    day: '27',
    title: 'Kuis Mingguan: Typography & Grids',
    course: 'Desain Grafis Dasar',
  },
  {
    month: 'Nov',
    day: '02',
    title: 'Proyek Akhir: Redesign Website Kampus',
    course: 'Web Development II',
    isPast: true,
  },
]

export const Feedbacks: IFeedbackItem[] = [
  {
    status: 'Lulus',
    time: '2 jam yang lalu',
    title: 'Visual Hierarchy Exercise',
    comment: 'Penggunaan white space sangat baik. Kontras pada judul sudah tepat.',
    instructor: {
      name: 'Sarah Wijaya, M.Ds.',
      avatar: 'https://picsum.photos/seed/sarah/100/100',
    },
  },
  {
    status: 'Perlu Revisi',
    time: 'Kemarin',
    title: 'User Research Report',
    comment: 'Data persona masih kurang mendalam. Coba tambahkan minimal 3 interview lagi.',
    instructor: {
      name: 'Dr. Anton Subekti',
      avatar: 'https://picsum.photos/seed/anton/100/100',
    },
  },
  {
    status: 'Lulus',
    time: '3 hari lalu',
    title: 'Introduction to Figma',
    comment: 'Sangat rapi! Penamaan layer sangat terorganisir. Bagus sekali.',
    instructor: {
      name: 'Nadia Putri',
      avatar: 'https://picsum.photos/seed/nadia/100/100',
    },
  },
  {
    status: 'Lulus',
    time: '2 jam yang lalu',
    title: 'Visual Hierarchy Exercise',
    comment: 'Penggunaan white space sangat baik. Kontras pada judul sudah tepat.',
    instructor: {
      name: 'Sarah Wijaya, M.Ds.',
      avatar: 'https://picsum.photos/seed/sarah/100/100',
    },
  },
  {
    status: 'Perlu Revisi',
    time: 'Kemarin',
    title: 'User Research Report',
    comment: 'Data persona masih kurang mendalam. Coba tambahkan minimal 3 interview lagi.',
    instructor: {
      name: 'Dr. Anton Subekti',
      avatar: 'https://picsum.photos/seed/anton/100/100',
    },
  },
  {
    status: 'Lulus',
    time: '3 hari lalu',
    title: 'Introduction to Figma',
    comment: 'Sangat rapi! Penamaan layer sangat terorganisir. Bagus sekali.',
    instructor: {
      name: 'Nadia Putri',
      avatar: 'https://picsum.photos/seed/nadia/100/100',
    },
  },
]

// Transaction data
export const statusStyles: Record<PaymentStatus, string> = {
  PAID: 'border-emerald-200 bg-emerald-50 text-emerald-700',
  PENDING: 'border-amber-200 bg-amber-50 text-amber-700',
  FAILED: 'border-rose-200 bg-rose-50 text-rose-700',
}

export const statusLabels: Record<PaymentStatus, string> = {
  PAID: 'Paid',
  PENDING: 'Pending',
  FAILED: 'Failed',
}

export const statusRank: Record<PaymentStatus, number> = {
  FAILED: 1,
  PENDING: 2,
  PAID: 3,
}

export const transactionsHistoryData: TransactionHistoryItem[] = [
  {
    uid: 'txn-a8f29h',
    transactionId: 'TRX-2026-0001',
    courseImage: 'https://picsum.photos/seed/webdu-trx-1/320/200',
    courseName: 'Full Stack Laravel 12 Bonus Project Vue Website Marketplace',
    classType: 'Premium',
    price: 478140,
    paymentStatus: 'PAID',
    purchasedAt: '2026-02-22T20:02:37',
    paymentMethod: 'Virtual Account',
  },
  {
    uid: 'txn-c1p76m',
    transactionId: 'TRX-2026-0002',
    courseImage: 'https://picsum.photos/seed/webdu-trx-2/320/200',
    courseName: 'Mastering React 19 Build Scalable Enterprise Frontend',
    classType: 'Premium',
    price: 350000,
    paymentStatus: 'PAID',
    purchasedAt: '2026-03-10T14:10:00',
    paymentMethod: 'Bank Transfer',
  },
  {
    uid: 'txn-k2m48r',
    transactionId: 'TRX-2026-0003',
    courseImage: 'https://picsum.photos/seed/webdu-trx-3/320/200',
    courseName: 'UI UX Design Masterclass for Product and Startup Team',
    classType: 'Free',
    price: 0,
    paymentStatus: 'PAID',
    purchasedAt: '2026-03-15T09:45:10',
    paymentMethod: 'E-Wallet',
  },
  {
    uid: 'txn-z9n24q',
    transactionId: 'TRX-2026-0004',
    courseImage: 'https://picsum.photos/seed/webdu-trx-4/320/200',
    courseName: 'Python Data Science Bootcamp with Portfolio Projects',
    classType: 'Bootcamp',
    price: 920000,
    paymentStatus: 'PENDING',
    purchasedAt: '2026-04-01T11:20:05',
    paymentMethod: 'Virtual Account',
  },
  {
    uid: 'txn-b4s67u',
    transactionId: 'TRX-2026-0005',
    courseImage: 'https://picsum.photos/seed/webdu-trx-5/320/200',
    courseName: 'Advanced CSS and Sass Flexbox Grid and Animation',
    classType: 'Premium',
    price: 275000,
    paymentStatus: 'FAILED',
    purchasedAt: '2026-04-04T16:45:12',
    paymentMethod: 'E-Wallet',
  },
  {
    uid: 'txn-j6v19t',
    transactionId: 'TRX-2026-0006',
    courseImage: 'https://picsum.photos/seed/webdu-trx-6/320/200',
    courseName: 'Backend Golang Clean Architecture from Beginner to Expert',
    classType: 'Premium',
    price: 410000,
    paymentStatus: 'PAID',
    purchasedAt: '2026-04-06T08:10:22',
    paymentMethod: 'Bank Transfer',
  },
  {
    uid: 'txn-r3w85n',
    transactionId: 'TRX-2026-0007',
    courseImage: 'https://picsum.photos/seed/webdu-trx-7/320/200',
    courseName: 'Data Analytics with SQL and Business Intelligence Dashboard',
    classType: 'Bootcamp',
    price: 760000,
    paymentStatus: 'PENDING',
    purchasedAt: '2026-04-07T10:18:42',
    paymentMethod: 'Virtual Account',
  },
  {
    uid: 'txn-f5l33y',
    transactionId: 'TRX-2026-0008',
    courseImage: 'https://picsum.photos/seed/webdu-trx-8/320/200',
    courseName: 'Build AI Assistant with Next.js and OpenAPI Integration',
    classType: 'Premium',
    price: 540000,
    paymentStatus: 'PAID',
    purchasedAt: '2026-04-08T19:32:19',
    paymentMethod: 'Bank Transfer',
  },
  {
    uid: 'txn-m7x20k',
    transactionId: 'TRX-2026-0009',
    courseImage: 'https://picsum.photos/seed/webdu-trx-9/320/200',
    courseName: 'Mobile App Design System for Android and iOS Team',
    classType: 'Premium',
    price: 305000,
    paymentStatus: 'FAILED',
    purchasedAt: '2026-04-09T13:56:50',
    paymentMethod: 'E-Wallet',
  },
  {
    uid: 'txn-p8h42d',
    transactionId: 'TRX-2026-0010',
    courseImage: 'https://picsum.photos/seed/webdu-trx-10/320/200',
    courseName: 'System Design Fundamentals for High Scale Application',
    classType: 'Bootcamp',
    price: 1100000,
    paymentStatus: 'PAID',
    purchasedAt: '2026-04-10T07:40:05',
    paymentMethod: 'Bank Transfer',
  },
  {
    uid: 'txn-g4q99e',
    transactionId: 'TRX-2026-0011',
    courseImage: 'https://picsum.photos/seed/webdu-trx-11/320/200',
    courseName: 'Product Management Roadmap for Junior to Mid Level PM',
    classType: 'Premium',
    price: 285000,
    paymentStatus: 'PAID',
    purchasedAt: '2026-04-10T10:11:41',
    paymentMethod: 'Virtual Account',
  },
  {
    uid: 'txn-y2d14b',
    transactionId: 'TRX-2026-0012',
    courseImage: 'https://picsum.photos/seed/webdu-trx-12/320/200',
    courseName: 'Docker and Kubernetes Practical Guide for Deployment Team',
    classType: 'Premium',
    price: 625000,
    paymentStatus: 'PENDING',
    purchasedAt: '2026-04-10T15:21:13',
    paymentMethod: 'Virtual Account',
  },
  {
    uid: 'txn-q1r88w',
    transactionId: 'TRX-2026-0013',
    courseImage: 'https://picsum.photos/seed/webdu-trx-13/320/200',
    courseName: 'Flutter Mobile Development Complete Guide with Firebase',
    classType: 'Premium',
    price: 485000,
    paymentStatus: 'PENDING',
    purchasedAt: new Date().toISOString(),
    paymentMethod: 'QRIS',
    qrImage: 'https://api.qrserver.com/v1/create-qr-code/?size=240x240&data=WEBDU-TRX-2026-0013-QRIS-485000',
  },
  {
    uid: 'txn-e3v55a',
    transactionId: 'TRX-2026-0014',
    courseImage: 'https://picsum.photos/seed/webdu-trx-14/320/200',
    courseName: 'Ethical Hacking and Penetration Testing Masterclass',
    classType: 'Bootcamp',
    price: 890000,
    paymentStatus: 'PENDING',
    purchasedAt: new Date().toISOString(),
    paymentMethod: 'E-Wallet',
  },
  {
    uid: 'txn-h7j22c',
    transactionId: 'TRX-2026-0015',
    courseImage: 'https://picsum.photos/seed/webdu-trx-15/320/200',
    courseName: 'Cloud Architecture AWS and GCP Professional Certification',
    classType: 'Bootcamp',
    price: 1250000,
    paymentStatus: 'PENDING',
    purchasedAt: new Date().toISOString(),
    paymentMethod: 'Bank Transfer',
  },
]

// Certificate data
export const DataCertificates: ICertificate[] = [
  {
    uid: 'crt-9f4c3a',
    title: 'Advanced React Architecture',
    courseName: 'Advanced React Patterns & Next.js 15 Architecture',
    issuedDate: '12 April 2026',
    category: 'Pengembangan Web',
    credentialId: 'WEB-DU-2026-REACT-0045',
    imageUrl: 'https://picsum.photos/seed/cert1/800/600',
  },
  {
    uid: 'crt-2b8e7d',
    title: 'Mastering Tailwind CSS v4',
    courseName: 'Mastering Tailwind CSS v4 & Framer Motion',
    issuedDate: '24 Maret 2026',
    category: 'Pengembangan Web',
    credentialId: 'WEB-DU-2026-TW-0112',
    imageUrl: 'https://picsum.photos/seed/cert2/800/600',
  },
  {
    uid: 'crt-1a5b9c',
    title: 'UI/UX Fundamentals Excellence',
    courseName: 'UI/UX Fundamentals',
    issuedDate: '15 Februari 2026',
    category: 'Desain UI/UX',
    credentialId: 'WEB-DU-2026-UIUX-0892',
    imageUrl: 'https://picsum.photos/seed/cert3/800/600',
  },
  {
    uid: 'crt-8d2f1e',
    title: 'Cybersecurity Analyst Certificate',
    courseName: 'Cybersecurity Analyst Bootcamp',
    issuedDate: '10 Januari 2026',
    category: 'Cybersecurity',
    credentialId: 'WEB-DU-2026-CYBER-0321',
    imageUrl: 'https://picsum.photos/seed/cert4/800/600',
  },
  {
    uid: 'crt-5c6a3b',
    title: 'Data Science Specialist',
    courseName: 'Machine Learning with Python: Zero to Hero',
    issuedDate: '05 Desember 2025',
    category: 'Data Science & AI',
    credentialId: 'WEB-DU-2025-ML-0754',
    imageUrl: 'https://picsum.photos/seed/cert5/800/600',
  },
]

// Attendance data
export const CourseAttendanceData: ICourseAttendance[] = [
  {
    courseId: 'crs-react-01',
    courseName: 'Advanced React Patterns & Next.js 15 Architecture',
    author: {
      name: 'Sarah Drasner',
      avatar: 'https://i.pravatar.cc/150?u=sarah_d',
    },
    image: 'https://picsum.photos/seed/react/600/400',
    summary: {
      totalMeetings: 12,
      hadir: 8,
      izin: 1,
      alpha: 1,
      progressPercentage: 80,
    },
    records: [
      { uid: 'rec-01', meetingNumber: 1, date: '02 September 2025', topic: 'Pengenalan React Architecture', status: 'Hadir' },
      { uid: 'rec-02', meetingNumber: 2, date: '09 September 2025', topic: 'Komponen Fundamental', status: 'Hadir' },
      { uid: 'rec-03', meetingNumber: 3, date: '16 September 2025', topic: 'Stateless dan Stateful', status: 'Izin', notes: 'Sakit' },
      { uid: 'rec-04', meetingNumber: 4, date: '23 September 2025', topic: 'React Hook: useState', status: 'Hadir' },
      { uid: 'rec-05', meetingNumber: 5, date: '30 September 2025', topic: 'React Hook: useEffect', status: 'Hadir' },
      { uid: 'rec-06', meetingNumber: 6, date: '07 Oktober 2025', topic: 'Custom Hooks', status: 'Hadir' },
      { uid: 'rec-07', meetingNumber: 7, date: '14 Oktober 2025', topic: 'Context API Dasar', status: 'Alpha' },
      { uid: 'rec-08', meetingNumber: 8, date: '21 Oktober 2025', topic: 'Review Materi', status: 'Hadir' },
      { uid: 'rec-09', meetingNumber: 9, date: '28 Oktober 2025', topic: 'Pengenalan Next.js Route', status: 'Hadir' },
      { uid: 'rec-10', meetingNumber: 10, date: '04 November 2025', topic: 'Server Component vs Client', status: 'Hadir' },
    ],
  },
  {
    courseId: 'crs-uiux-02',
    courseName: 'UI/UX Fundamentals',
    author: {
      name: 'Jessica Wong',
      avatar: 'https://i.pravatar.cc/150?u=jess_w',
    },
    image: 'https://picsum.photos/seed/uiux/600/400',
    summary: {
      totalMeetings: 8,
      hadir: 8,
      izin: 0,
      alpha: 0,
      progressPercentage: 100,
    },
    records: [
      { uid: 'rec-11', meetingNumber: 1, date: '10 September 2025', topic: 'Design Thinking', status: 'Hadir' },
      { uid: 'rec-12', meetingNumber: 2, date: '17 September 2025', topic: 'Wireframing', status: 'Hadir' },
      { uid: 'rec-13', meetingNumber: 3, date: '24 September 2025', topic: 'Prototyping', status: 'Hadir' },
      { uid: 'rec-14', meetingNumber: 4, date: '01 Oktober 2025', topic: 'User Testing', status: 'Hadir' },
      { uid: 'rec-15', meetingNumber: 5, date: '08 Oktober 2025', topic: 'Visual Hierarchy', status: 'Hadir' },
      { uid: 'rec-16', meetingNumber: 6, date: '15 Oktober 2025', topic: 'Color Theory', status: 'Hadir' },
      { uid: 'rec-17', meetingNumber: 7, date: '22 Oktober 2025', topic: 'Typography', status: 'Hadir' },
      { uid: 'rec-18', meetingNumber: 8, date: '29 Oktober 2025', topic: 'Final Review', status: 'Hadir' },
    ],
  },
  {
    courseId: 'crs-tailwind-03',
    courseName: 'Mastering Tailwind CSS v4 & Framer Motion',
    author: {
      name: 'Marcus Levin',
      avatar: 'https://i.pravatar.cc/150?u=marcus_l',
    },
    image: 'https://picsum.photos/seed/tailwind/600/400',
    summary: {
      totalMeetings: 10,
      hadir: 4,
      izin: 0,
      alpha: 1,
      progressPercentage: 50,
    },
    records: [
      { uid: 'rec-19', meetingNumber: 1, date: '05 September 2025', topic: 'Utility-first Concept', status: 'Hadir' },
      { uid: 'rec-20', meetingNumber: 2, date: '12 September 2025', topic: 'Setup & Installation', status: 'Hadir' },
      { uid: 'rec-21', meetingNumber: 3, date: '19 September 2025', topic: 'Layouting Flexbox', status: 'Alpha' },
      { uid: 'rec-22', meetingNumber: 4, date: '26 September 2025', topic: 'Layouting Grid', status: 'Hadir' },
      { uid: 'rec-23', meetingNumber: 5, date: '03 Oktober 2025', topic: 'Responsive Design', status: 'Hadir' },
    ],
  },
]

// Profile data
export const ProfileData = {
  uid: 'usr-8921md',
  name: 'Zapp',
  email: 'saptogusty@gmail.com',
  role: 'STUDENT',
  avatar: 'https://i.pravatar.cc/150?img=11',
  lastUpdated: '12 Apr 2026',
}

// Mentor Dashboard data
export const MentorDashboardStats: IMentorStats = {
  pendingGrading: 12,
  unansweredQA: 5,
  activeStudents: 24,
  totalCourses: 4,
}

export const MentorScheduleItems: IScheduleItem[] = [
  {
    uid: 'sch-001',
    courseId: 'crs-react-01',
    courseName: 'Advanced React Patterns & Next.js 15 Architecture',
    scheduleDate: '13 April 2026',
    scheduleTime: '09:00',
    endTime: '11:00',
    location: 'Zoom - Room 1',
    classType: 'online',
    studentCount: 28,
  },
  {
    uid: 'sch-002',
    courseId: 'crs-uiux-02',
    courseName: 'UI/UX Fundamentals',
    scheduleDate: '13 April 2026',
    scheduleTime: '14:00',
    endTime: '16:00',
    location: 'Ruang 201, Gedung A',
    classType: 'offline',
    studentCount: 24,
  },
  {
    uid: 'sch-003',
    courseId: 'crs-tailwind-03',
    courseName: 'Mastering Tailwind CSS v4 & Framer Motion',
    scheduleDate: '14 April 2026',
    scheduleTime: '10:00',
    endTime: '12:00',
    location: 'Zoom - Room 2',
    classType: 'online',
    studentCount: 19,
  },
  {
    uid: 'sch-004',
    courseId: 'crs-python-04',
    courseName: 'Python Data Science & Machine Learning',
    scheduleDate: '14 April 2026',
    scheduleTime: '13:00',
    endTime: '15:00',
    location: 'Ruang 301, Gedung B',
    classType: 'offline',
    studentCount: 22,
  },
  {
    uid: 'sch-005',
    courseId: 'crs-react-01',
    courseName: 'Advanced React Patterns & Next.js 15 Architecture',
    scheduleDate: '15 April 2026',
    scheduleTime: '08:00',
    endTime: '10:00',
    location: 'Zoom - Room 1',
    classType: 'online',
    studentCount: 28,
  },
  {
    uid: 'sch-006',
    courseId: 'crs-golang-05',
    courseName: 'Go (Golang) Microservices & Backend',
    scheduleDate: '15 April 2026',
    scheduleTime: '15:00',
    endTime: '17:00',
    location: 'Ruang 102, Gedung A',
    classType: 'offline',
    studentCount: 18,
  },
  {
    uid: 'sch-007',
    courseId: 'crs-uiux-02',
    courseName: 'UI/UX Fundamentals',
    scheduleDate: '16 April 2026',
    scheduleTime: '11:00',
    endTime: '13:00',
    location: 'Zoom - Room 3',
    classType: 'online',
    studentCount: 24,
  },
  {
    uid: 'sch-008',
    courseId: 'crs-cyber-06',
    courseName: 'Cybersecurity Analyst Bootcamp',
    scheduleDate: '17 April 2026',
    scheduleTime: '09:00',
    endTime: '11:30',
    location: 'Ruang 401, Gedung C',
    classType: 'offline',
    studentCount: 15,
  },
]

export const MentorSubmissionItems: ISubmissionItem[] = [
  {
    uid: 'sub-001',
    studentName: 'Ahmad Rizki',
    studentAvatar: 'https://i.pravatar.cc/150?u=ahmad_r',
    courseName: 'Advanced React Patterns & Next.js 15 Architecture',
    assignmentTitle: 'Build Custom React Hook Library',
    submissionDate: '12 April 2026 14:30',
    status: 'Submitted',
  },
  {
    uid: 'sub-002',
    studentName: 'Siti Nurhaliza',
    studentAvatar: 'https://i.pravatar.cc/150?u=siti_n',
    courseName: 'UI/UX Fundamentals',
    assignmentTitle: 'Mobile App Redesign Project',
    submissionDate: '11 April 2026 09:15',
    status: 'Submitted',
  },
  {
    uid: 'sub-003',
    studentName: 'Budi Santoso',
    studentAvatar: 'https://i.pravatar.cc/150?u=budi_s',
    courseName: 'Mastering Tailwind CSS v4 & Framer Motion',
    assignmentTitle: 'Responsive Dashboard Build',
    submissionDate: '10 April 2026 16:45',
    status: 'Late',
    daysLate: 2,
  },
  {
    uid: 'sub-004',
    studentName: 'Rina Wijaya',
    studentAvatar: 'https://i.pravatar.cc/150?u=rina_w',
    courseName: 'Advanced React Patterns & Next.js 15 Architecture',
    assignmentTitle: 'State Management with Context API',
    submissionDate: '09 April 2026 13:20',
    status: 'Submitted',
  },
  {
    uid: 'sub-005',
    studentName: 'Doni Hermanto',
    studentAvatar: 'https://i.pravatar.cc/150?u=doni_h',
    courseName: 'Python Data Science & Machine Learning',
    assignmentTitle: 'Data Analysis & Visualization',
    submissionDate: 'Pending',
    status: 'Pending',
  },
  {
    uid: 'sub-006',
    studentName: 'Lestari Putri',
    studentAvatar: 'https://i.pravatar.cc/150?u=lestari_p',
    courseName: 'UI/UX Fundamentals',
    assignmentTitle: 'User Research Report',
    submissionDate: '08 April 2026 11:00',
    status: 'Late',
    daysLate: 4,
  },
]
