import type { IMentorCourseStudent } from '@/lib/types'
import { isMockDataEnabled } from '@/lib/config/mock-data'

const MEETINGS_MC001 = 12
const MEETINGS_MC002 = 10

/** Fixture peserta per courseUid; nonaktif saat mock dimatikan — ganti dengan GET dari API. */
const STUDENTS_BY_COURSE: Record<string, IMentorCourseStudent[]> = {
  'crs-001': [
    {
      uid: 'stu-mc001-1',
      name: 'Aditya Pratama',
      email: 'aditya.p@mail.test',
      progressPercent: 92,
      attendancePresent: 11,
      attendanceTotal: MEETINGS_MC001,
      status: 'Aktif',
      lastActiveLabel: '2 jam lalu',
    },
    {
      uid: 'stu-mc001-2',
      name: 'Siti Nurhaliza',
      email: 'siti.n@mail.test',
      progressPercent: 78,
      attendancePresent: 9,
      attendanceTotal: MEETINGS_MC001,
      status: 'Aktif',
      lastActiveLabel: 'Kemarin',
    },
    {
      uid: 'stu-mc001-3',
      name: 'Budi Santoso',
      email: 'budi.s@mail.test',
      progressPercent: 100,
      attendancePresent: 12,
      attendanceTotal: MEETINGS_MC001,
      status: 'Selesai',
      lastActiveLabel: '3 hari lalu',
    },
    {
      uid: 'stu-mc001-4',
      name: 'Citra Dewi',
      email: 'citra.d@mail.test',
      progressPercent: 45,
      attendancePresent: 6,
      attendanceTotal: MEETINGS_MC001,
      status: 'Terlambat',
      lastActiveLabel: '5 hari lalu',
    },
    {
      uid: 'stu-mc001-5',
      name: 'Eko Wijaya',
      email: 'eko.w@mail.test',
      progressPercent: 88,
      attendancePresent: 10,
      attendanceTotal: MEETINGS_MC001,
      status: 'Aktif',
      lastActiveLabel: '1 jam lalu',
    },
    {
      uid: 'stu-mc001-6',
      name: 'Fitri Handayani',
      email: 'fitri.h@mail.test',
      progressPercent: 0,
      attendancePresent: 0,
      attendanceTotal: MEETINGS_MC001,
      status: 'Belum mulai',
      lastActiveLabel: '—',
    },
    {
      uid: 'stu-mc001-7',
      name: 'Gilang Ramadhan',
      email: 'gilang.r@mail.test',
      progressPercent: 67,
      attendancePresent: 8,
      attendanceTotal: MEETINGS_MC001,
      status: 'Aktif',
      lastActiveLabel: '4 jam lalu',
    },
    {
      uid: 'stu-mc001-8',
      name: 'Hana Putri',
      email: 'hana.p@mail.test',
      progressPercent: 100,
      attendancePresent: 11,
      attendanceTotal: MEETINGS_MC001,
      status: 'Selesai',
      lastActiveLabel: '1 minggu lalu',
    },
    {
      uid: 'stu-mc001-9',
      name: 'Indra Kusuma',
      email: 'indra.k@mail.test',
      progressPercent: 54,
      attendancePresent: 7,
      attendanceTotal: MEETINGS_MC001,
      status: 'Terlambat',
      lastActiveLabel: '2 hari lalu',
    },
    {
      uid: 'stu-mc001-10',
      name: 'Jessica Lim',
      email: 'jessica.l@mail.test',
      progressPercent: 95,
      attendancePresent: 12,
      attendanceTotal: MEETINGS_MC001,
      status: 'Aktif',
      lastActiveLabel: '30 menit lalu',
    },
    {
      uid: 'stu-mc001-11',
      name: 'Kevin Tan',
      email: 'kevin.t@mail.test',
      progressPercent: 71,
      attendancePresent: 9,
      attendanceTotal: MEETINGS_MC001,
      status: 'Aktif',
      lastActiveLabel: 'Kemarin',
    },
    {
      uid: 'stu-mc001-12',
      name: 'Lina Marlina',
      email: 'lina.m@mail.test',
      progressPercent: 33,
      attendancePresent: 4,
      attendanceTotal: MEETINGS_MC001,
      status: 'Terlambat',
      lastActiveLabel: '6 hari lalu',
    },
    {
      uid: 'stu-mc001-13',
      name: 'Michael Ong',
      email: 'michael.o@mail.test',
      progressPercent: 82,
      attendancePresent: 10,
      attendanceTotal: MEETINGS_MC001,
      status: 'Aktif',
      lastActiveLabel: '3 jam lalu',
    },
    {
      uid: 'stu-mc001-14',
      name: 'Nadia Fauzia',
      email: 'nadia.f@mail.test',
      progressPercent: 61,
      attendancePresent: 8,
      attendanceTotal: MEETINGS_MC001,
      status: 'Aktif',
      lastActiveLabel: '1 hari lalu',
    },
  ],
  'crs-002': [
    {
      uid: 'stu-mc002-1',
      name: 'Omar Hakim',
      email: 'omar.h@mail.test',
      progressPercent: 90,
      attendancePresent: 9,
      attendanceTotal: MEETINGS_MC002,
      status: 'Aktif',
      lastActiveLabel: '5 jam lalu',
    },
    {
      uid: 'stu-mc002-2',
      name: 'Putri Ayu',
      email: 'putri.a@mail.test',
      progressPercent: 100,
      attendancePresent: 10,
      attendanceTotal: MEETINGS_MC002,
      status: 'Selesai',
      lastActiveLabel: '2 hari lalu',
    },
    {
      uid: 'stu-mc002-3',
      name: 'Rizki Maulana',
      email: 'rizki.m@mail.test',
      progressPercent: 55,
      attendancePresent: 6,
      attendanceTotal: MEETINGS_MC002,
      status: 'Terlambat',
      lastActiveLabel: '4 hari lalu',
    },
    {
      uid: 'stu-mc002-4',
      name: 'Salsa Amira',
      email: 'salsa.a@mail.test',
      progressPercent: 74,
      attendancePresent: 8,
      attendanceTotal: MEETINGS_MC002,
      status: 'Aktif',
      lastActiveLabel: 'Kemarin',
    },
    {
      uid: 'stu-mc002-5',
      name: 'Taufik Hidayat',
      email: 'taufik.h@mail.test',
      progressPercent: 12,
      attendancePresent: 2,
      attendanceTotal: MEETINGS_MC002,
      status: 'Belum mulai',
      lastActiveLabel: '—',
    },
    {
      uid: 'stu-mc002-6',
      name: 'Umi Kalsum',
      email: 'umi.k@mail.test',
      progressPercent: 68,
      attendancePresent: 7,
      attendanceTotal: MEETINGS_MC002,
      status: 'Aktif',
      lastActiveLabel: '1 jam lalu',
    },
    {
      uid: 'stu-mc002-7',
      name: 'Vino Bastian',
      email: 'vino.b@mail.test',
      progressPercent: 85,
      attendancePresent: 9,
      attendanceTotal: MEETINGS_MC002,
      status: 'Aktif',
      lastActiveLabel: '3 jam lalu',
    },
    {
      uid: 'stu-mc002-8',
      name: 'Wulan Sari',
      email: 'wulan.s@mail.test',
      progressPercent: 96,
      attendancePresent: 10,
      attendanceTotal: MEETINGS_MC002,
      status: 'Selesai',
      lastActiveLabel: '5 hari lalu',
    },
    {
      uid: 'stu-mc002-9',
      name: 'Yoga Prasetyo',
      email: 'yoga.p@mail.test',
      progressPercent: 41,
      attendancePresent: 5,
      attendanceTotal: MEETINGS_MC002,
      status: 'Terlambat',
      lastActiveLabel: '1 minggu lalu',
    },
    {
      uid: 'stu-mc002-10',
      name: 'Zahra Indira',
      email: 'zahra.i@mail.test',
      progressPercent: 79,
      attendancePresent: 8,
      attendanceTotal: MEETINGS_MC002,
      status: 'Aktif',
      lastActiveLabel: '12 jam lalu',
    },
  ],
  'crs-003': [
    {
      uid: 'stu-mc003-1',
      name: 'Maya Kusuma',
      email: 'maya.k@mail.test',
      progressPercent: 55,
      attendancePresent: 3,
      attendanceTotal: 5,
      status: 'Aktif',
      lastActiveLabel: '1 hari lalu',
    },
    {
      uid: 'stu-mc003-2',
      name: 'Nando Gibran',
      email: 'nando.g@mail.test',
      progressPercent: 88,
      attendancePresent: 5,
      attendanceTotal: 5,
      status: 'Selesai',
      lastActiveLabel: '3 hari lalu',
    },
    {
      uid: 'stu-mc003-3',
      name: 'Oki Pratama',
      email: 'oki.p@mail.test',
      progressPercent: 22,
      attendancePresent: 1,
      attendanceTotal: 5,
      status: 'Terlambat',
      lastActiveLabel: 'Kemarin',
    },
  ],
  'crs-004': [
    {
      uid: 'stu-mc004-1',
      name: 'Pandu Wijaya',
      email: 'pandu.w@mail.test',
      progressPercent: 71,
      attendancePresent: 2,
      attendanceTotal: 3,
      status: 'Aktif',
      lastActiveLabel: '4 jam lalu',
    },
    {
      uid: 'stu-mc004-2',
      name: 'Qori Sandria',
      email: 'qori.s@mail.test',
      progressPercent: 40,
      attendancePresent: 1,
      attendanceTotal: 3,
      status: 'Belum mulai',
      lastActiveLabel: '—',
    },
  ],
}

export function getMentorCourseStudents(courseUid: string): IMentorCourseStudent[] {
  if (!isMockDataEnabled()) return []
  const list = STUDENTS_BY_COURSE[courseUid]
  if (list) return list
  return []
}
